#pragma once

#define ITEMTYPE_NUM 6

enum WIDGETTYPE {EXIT, LOGOWIDGET, LOGINWIDGET, SELECTWIDGET, GAMEWIDGET, ITEMLISTWIDGET, TUTORIALWIDGET, SHOPWIDGET, STATUSWIDGET, REPLAYWIDGET};
enum TEAM {ATEAM, BTEAM};
enum SIGNUP {EXISTING_ID, NO_ID, NO_PWD, DIFFERENT_REPWD, SUCCESS_SIGNUP};
enum ENTER {NOEXISTING_ID, SAME_ID, DIFFERENT_PWD, SUCCESS_ENTER};

